In [2]:
import numpy as np
from scipy import stats

# Ex 1)

In [3]:
# a)
mean =  2
var = np.sqrt(0.16)
stats.norm.cdf((1.8 - mean) / var)

0.30853753872598694

In [4]:
# b)
(stats.norm.cdf((2.1 - mean) / var)) - stats.norm.cdf((1.8 - mean) / var)

0.2901687869569369

In [5]:
# c)
1 - stats.norm.cdf((2.3 - mean) / var)

0.22662735237686826

# Ex 3

In [6]:
import math
mean = 8
var = 8
math.pow(math.e, - 10/8)

0.2865047968601901

In [7]:
1 - stats.expon.cdf(10, scale=8)

0.28650479686019015

In [8]:
stats.expon.cdf(mean, scale=mean)

0.6321205588285577

In [9]:
stats.expon.cdf(11, scale=mean) - stats.expon.cdf(5, scale=mean)

0.2824218327142438

# Ex 4

In [10]:
u = [1, 1]
v = [1, -1]
s = [15, 9]
np.linalg.solve([u, v], s)

array([12.,  3.])

# Ex 5

In [11]:
# a)
y = lambda x: 2 * x + 5
a = y(0)
b = y(1)

f = lambda x: 1 / (b - a)

In [12]:
# b)
E = (a + b) / 2
V = math.pow(a - b, 2) / 12

print(E, V)

6.0 0.3333333333333333


# Ex 6

In [13]:
np.argmax(stats.norm.cdf(np.arange(-3, 3, 0.01)) > 0.05)

136

In [14]:
np.arange(-3, 3, 0.01)[136]

-1.640000000000029

In [15]:
x = (29.5 + np.arange(-3, 3, 0.01)[136] * 2.5)
print(x)

25.399999999999928


# Ex 7

a)
a = -alpha
b = alpha
(x_2 - a) / (b - a) - (x_1 - a) / (b - a) == 3 / 4

x_2 - x_1 = 3/4 * b - 3/4 * a
3 = 3/2 * alpha
alpha = 2

b)
2 / alpha = (2 - alpha) / (alpha) - 1
2 = alpha ^ 2

# Ex 8

In [16]:
# a)
stats.uniform.sf(353, loc=345, scale=10)

0.19999999999999996

In [17]:
# b)
stats.uniform.cdf(346, loc=345, scale=10)

0.1

In [18]:
# c)
stats.uniform.cdf(346, loc=345, scale=10) + stats.uniform.sf(354, loc=345, scale=10)

0.19999999999999998

# Ex 9

In [19]:
# a)
stats.expon.sf(10, scale=12)

0.4345982085070782

In [20]:
# b)
stats.expon.cdf(8, scale=12)

0.486582880967408

# Ex 10

(a + b) / 2 = lambda
(a - b) / sqrt(12) = lambda
a = 2 * mean - b
a = sqrt(12) * sigma + b
2 * mean - sqrt(12) * sigma = 2 * b
b = mean - sqrt(12) * sigma / 2
a = mean + sqrt(12) * sigma / 2

# Ex 11

In [21]:
mean = 1000
p = 0.01
x = 990

In [22]:
v_s = np.arange(-3, -1, 0.0001)
v = v_s[np.argmax(stats.norm.cdf(v_s) >= 0.01)]
std = round((x - mean) / v, 6)
print(std)

4.298672


# Ex 12

In [23]:
f_y_x = np.array([
    [1/12, 1/6, 0],
    [0, 1/9, 1/5],
    [1/18, 1/4, 2/15]
])

In [24]:
g_y = np.sum(f_y_x, axis=0)
h_x = np.sum(f_y_x.T, axis=0)

In [25]:
P_y_x = f_y_x / g_y
P_x_y = f_y_x / h_x

In [26]:
print(h_x, ", ", g_y, end="\n\n")
print(P_x_y)
print(P_y_x)

[0.25       0.31111111 0.43888889] ,  [0.13888889 0.52777778 0.33333333]

[[0.33333333 0.53571429 0.        ]
 [0.         0.35714286 0.4556962 ]
 [0.22222222 0.80357143 0.30379747]]
[[0.6        0.31578947 0.        ]
 [0.         0.21052632 0.6       ]
 [0.4        0.47368421 0.4       ]]


# Ex 13

In [27]:
f_x_y = np.array([
    [0.1, 0.2, 0.1, 0.2],
    [0.2, 0, 0.1, 0.1]
])

In [28]:
h_x = np.sum(f_x_y.T, axis=0)
g_y = np.sum(f_x_y, axis=0)

In [29]:
h_x, g_y

(array([0.6, 0.4]), array([0.3, 0.2, 0.2, 0.3]))

In [30]:
# b)
np.max([
    [
        f_x_y[x][y] == sum(f_x_y[x, :]) * sum(f_x_y[:, y])
        for x in range(2)
    ]
    for y in range(4)
])

False

# Ex 14

In [42]:
f_y_x = np.array([
    [1/12, 1/60, 7/40],
    [1/8, 1/12, 1/30],
    [1/24, 1/24, 1/4],
    [1/12, 1/40, 1/24]
])
f_x_y = f_y_x.T

In [43]:
h_x = np.sum(f_x_y.T, axis=0)
g_y = np.sum(f_x_y, axis=0)

In [55]:
sum(f_x_y[0, 1:3]) / sum(g_y[1:3])

0.2898550724637681

In [63]:
sum(np.arange(3) * f_x_y[:, 3])

0.10833333333333334

In [76]:
x, y = np.meshgrid(range(3), range(4))
var = np.sum((x + y)**2 * f_y_x) - np.sum((x + y) * f_y_x)**2

In [77]:
var

1.8327083333333318

# Ex 15

In [33]:
# a)
f_x_y = np.array([
    [0.36, 0.24, 0.0],
    [0.0, 0.24, 0.16]
])

In [34]:
h_x = np.sum(f_x_y.T, axis=0)
g_y = np.sum(f_x_y, axis=0)

In [35]:
h_x, g_y

(array([0.6, 0.4]), array([0.36, 0.48, 0.16]))

In [36]:
# b)
P_x_y = f_x_y / g_y
P_x_y

array([[1. , 0.5, 0. ],
       [0. , 0.5, 1. ]])

In [37]:
# c)
sum(sum(f_x_y[:, 1:]))

0.64

# Ex 16

In [38]:
# a)
f_x_y = np.array([[x*y for x in range(1, 4)] for y in range(1, 4)])
k = 1 / f_x_y.sum()
print(k == 1/36)

True


In [39]:
# b)
# fiz no papel (integral)
k = 1 / 210

# 17 e 18

In [40]:
# Fiz no papel