In [30]:
import numpy as np
import math as m

import numpy as np
import math as m

# QR 
def clgsQR(A):
    (m,n) = np.shape(A);
    Q = np.zeros((m,n));
    R = np.zeros((n,n));

    for j in np.arange(n):
        V = A[:,j];
        for i in np.arange(j):
            R[i,j] = Q[:,i].dot(A[:,j]); 
            V = V - R[i,j]*Q[:,i];
        R[j,j] = np.linalg.norm(V);
        Q[:,j] = V/R[j,j];

    return Q,R

# QR modificado
def mgsQR(A):
    (m,n) = np.shape(A);
    V = np.copy(A); 
    Q = np.zeros((m,n));
    R = np.zeros((n,n));

    for j in np.arange(n):
        for i in np.arange(j):
            R[i,j] = Q[:,i].dot(V[:,j]); 
            V[:,j] = V[:,j] - R[i,j]*Q[:,i];
        R[j,j] = np.linalg.norm(V[:,j]);
        Q[:,j] = V[:,j]/R[j,j];

    return Q,R

# Exemplo




#B = np.array([[1, 1, 1],  
 #             [1e-20, 0, 0],  
 #             [0, 1e-20, 0],
 #             [0, 0, 1e-20]], dtype='double')

B = np.array([[1, 1, 1],  
              [1, 0, 2],  
              [1, 0, 1],
              [0, 1, 3]], dtype='double')
print(B)
(m,n) = np.shape(B);

print('Calculando decomposição QR clássica\n')
(Q_c,R_c) = clgsQR(B);
print(Q_c); print(R_c);

print('Calculando o erro da decomposição QR clássica')
B_calc = Q_c.dot(R_c); 
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_c).dot(Q_c);
I = np.eye(n);
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

#input("\n")

print('Calculando decomposição QR modificada\n')
(Q_c,R_c) = mgsQR(B);
print(Q_c); print(R_c);

print('Calculando o erro da decomposição QR modificada')
B_calc = Q_c.dot(R_c); 
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_c).dot(Q_c);
I = np.eye(n);
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

# Comparando com a do Python
(Q_python,R_python) = np.linalg.qr(B)
print(Q_python)
print(R_python)
#print(Q_python.dot(R_python))

print('Calculando o erro da decomposição QR Python')
B_calc = Q_python.dot(R_python); 
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_python).dot(Q_python);
I = np.eye(n);
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

[[1. 1. 1.]
 [1. 0. 2.]
 [1. 0. 1.]
 [0. 1. 3.]]
Calculando decomposição QR clássica

[[ 0.57735027  0.51639778 -0.60246408]
 [ 0.57735027 -0.25819889  0.51639778]
 [ 0.57735027 -0.25819889  0.0860663 ]
 [ 0.          0.77459667  0.60246408]]
[[1.73205081 0.57735027 2.30940108]
 [0.         1.29099445 2.06559112]
 [0.         0.         2.32379001]]
Calculando o erro da decomposição QR clássica
O erro da decomposição é: 2.22e-16

Calculando o erro de ortogonalidade
O erro de ortogonalidade é: 4.41e-16

Calculando decomposição QR modificada

[[ 0.57735027  0.51639778 -0.60246408]
 [ 0.57735027 -0.25819889  0.51639778]
 [ 0.57735027 -0.25819889  0.0860663 ]
 [ 0.          0.77459667  0.60246408]]
[[1.73205081 0.57735027 2.30940108]
 [0.         1.29099445 2.06559112]
 [0.         0.         2.32379001]]
Calculando o erro da decomposição QR modificada
O erro da decomposição é: 2.22e-16

Calculando o erro de ortogonalidade
O erro de ortogonalidade é: 4.41e-16

[[-0.57735027  0.51639778  0.