In [2]:


import numpy as np
import math as m

# QR 
def clgsQR(A):
    (m,n) = np.shape(A);
    Q = np.zeros((m,n));
    R = np.zeros((n,n));

    for j in np.arange(n):
        V = A[:,j];
        for i in np.arange(j):
            R[i,j] = Q[:,i].dot(A[:,j]); 
            V = V - R[i,j]*Q[:,i];
        R[j,j] = np.linalg.norm(V);
        Q[:,j] = V/R[j,j];

    return Q,R

# QR modificado
def mgsQR(A):
    (m,n) = np.shape(A);
    V = np.copy(A); 
    Q = np.zeros((m,n));
    R = np.zeros((n,n));

    for j in np.arange(n):
        for i in np.arange(j):
            R[i,j] = Q[:,i].dot(V[:,j]); 
            V[:,j] = V[:,j] - R[i,j]*Q[:,i];
        R[j,j] = np.linalg.norm(V[:,j]);
        Q[:,j] = V[:,j]/R[j,j];

    return Q,R

# Exemplo
B = np.array([[1, 1, 0],  
              [0, 1, 2],  
              [1, 0, 1],
              [0, 1, 3]], dtype='double')
print(B)
(m,n) = np.shape(B);

print('Calculando decomposição QR clássica\n')
(Q_c,R_c) = clgsQR(B);
print(Q_c); print(R_c);

print('Calculando o erro da decomposição QR clássica')
B_calc = Q_c.dot(R_c); 
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_c).dot(Q_c);
I = np.eye(n);
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

print('Calculando decomposição QR modificada\n')
(Q_c,R_c) = mgsQR(B);
print(Q_c); print(R_c);

print('Calculando o erro da decomposição QR modificada')
B_calc = Q_c.dot(R_c); 
norm_B = np.linalg.norm(B-B_calc,'fro')
print('O erro da decomposição é: %.2e\n' %(norm_B))

print('Calculando o erro de ortogonalidade')
I_calc = np.transpose(Q_c).dot(Q_c);
I = np.eye(n);
norm_I = np.linalg.norm(I-I_calc,'fro')
print('O erro de ortogonalidade é: %.2e\n' %(norm_I))

########################################################################################################################

# Francis
def francis(A,tol):
    qr = np.linalg.qr;
    
    n = np.shape(A)[0];
    A_local = np.copy(A);
    V = np.eye(n);
    erro = np.inf

    while erro > tol:
        [Q,R] = qr(A_local);
        A_local = R.dot(Q);
        V = V.dot(Q);

        erro = np.max(np.max(np.abs(np.tril(A_local,-1))));
    
    D = np.diag(A_local);

    return D,V

def get_random_matrix(n=7, m=5):
    A = np.random.rand(n, m).astype(np.float64)

    return A

def test_francis():
    A = get_random_matrix()
    symmetric = A.T.dot(A)

    V, D = np.linalg.eig(symmetric)

    print(np.allclose(symmetric @ V, D * V))

test_francis()

[[1. 1. 0.]
 [0. 1. 2.]
 [1. 0. 1.]
 [0. 1. 3.]]
Calculando decomposição QR clássica

[[ 0.70710678  0.31622777 -0.60246408]
 [ 0.          0.63245553  0.0860663 ]
 [ 0.70710678 -0.31622777  0.60246408]
 [ 0.          0.63245553  0.51639778]]
[[1.41421356 0.70710678 0.70710678]
 [0.         1.58113883 2.84604989]
 [0.         0.         2.32379001]]
Calculando o erro da decomposição QR clássica
O erro da decomposição é: 7.26e-17

Calculando o erro de ortogonalidade
O erro de ortogonalidade é: 3.91e-16

Calculando decomposição QR modificada

[[ 0.70710678  0.31622777 -0.60246408]
 [ 0.          0.63245553  0.0860663 ]
 [ 0.70710678 -0.31622777  0.60246408]
 [ 0.          0.63245553  0.51639778]]
[[1.41421356 0.70710678 0.70710678]
 [0.         1.58113883 2.84604989]
 [0.         0.         2.32379001]]
Calculando o erro da decomposição QR modificada
O erro da decomposição é: 7.26e-17

Calculando o erro de ortogonalidade
O erro de ortogonalidade é: 3.91e-16

False
