In [5]:
import numpy as np
import math as m

# Gauss-Jacobi
def gauss_jacobi(A,b,x0,tol,flag):
    n = np.shape(A)[0];
    D = np.diag(np.diag(A));
    aux_C = np.linalg.solve(D,A);
    C = np.eye(n) - aux_C;
    g = np.linalg.solve(D,b);
    kmax = 10000; k = 0;

    error = np.zeros(kmax);
    if flag:
        statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax);
    else:
        statment = (k<kmax);

    while statment:
        error[k] = np.linalg.norm(b-A.dot(x0));
        k = k+1;
        x0 = C.dot(x0)+g;
        if flag:
            statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax);
        else:
            statment = (k<kmax);
    
    if (k == kmax and flag):
        print('\nErro: o método não converge.\n')
    
    x = x0;
    return x,k,error

# Gauss-Seidel
def gauss_seidel(A,b,x0,tol,flag):
    L = np.tril(A); R = np.triu(A,1);
    C = -np.linalg.solve(L,R);
    print(L, R)
    g = np.linalg.solve(L,b);
    kmax = 10000; k = 0;

    error = np.zeros(kmax); 

    if flag: 
        statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax);
    else:
        statment = (k<kmax);
        
    while statment:
        error[k] = np.linalg.norm(b-A.dot(x0));
        k = k+1;
        x0 = C.dot(x0)+g;
        if flag:
            statment = (np.linalg.norm(b-A.dot(x0))>tol and k<kmax);
        else:
            statment = (k<kmax);

    if (k == kmax and flag):
        print('\nErro: o método não converge.\n')
    
    x = x0;
    return x,k,error

# Exemplo
A = np.array([[ -8, 1, 1],  
              [ 1, -5, 1],  
              [1, 1, -4]], dtype='double')
b = np.array([1,16,7], dtype='double')

x0 = np.zeros(len(A))
tol = 1e-8

print('\nSolução Gauss-Siedel:\n')
(x_siedel,k_siedel,erro_siedel) = gauss_seidel(A,b,x0,tol,1);
print(x_siedel);


Solução Gauss-Siedel:

[[-8.  0.  0.]
 [ 1. -5.  0.]
 [ 1.  1. -4.]] [[0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
[-1. -4. -3.]
